### Numpy Installation
- !pip install numpy==1.26.4    specific version installation
- !pip install "numpy<=1.26.4"  for conditional installation
- !pip install numpy            install latest version

In [2]:
!pip install numpy

   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.8 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.8 MB 4.0 MB/s eta 0:00:03
   ---- ----------------------------------- 1.6/12.8 MB 2.5 MB/s eta 0:00:05
   ------ --------------------------------- 2.1/12.8 MB 2.9 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.8 MB 2.9 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.8 MB 2.9 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.8 MB 2.8 MB/s eta 0:00:04
   ------------- -------------------------- 4.5/12.8 MB 2.7 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.8 MB 2.6 MB/s eta 0:00:04
   ---------------- ----------------------- 5.2/12.8 MB 2.5 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.8 MB 2.4 MB/s eta 0:00:03
   ------------------ --------------------- 6.0/12.8 MB 2.3 MB/s eta 0:00:03
   ---

In [1]:
import numpy

In [3]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [4]:
tuple(list)

(1, 2, 3, 4, 5)

### Creating numpy array

In [27]:
arr0=numpy.array(10)
arr0

array(10)

In [28]:
arr0.ndim

0

In [6]:
arr=numpy.array(list)
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [11]:
l1=[[[[[[[[[[[[[4,5]]]]]]]]]]]]]
arr1=numpy.array(l1)
arr1.ndim

13

In [14]:
arr1.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2)

In [9]:
# num of dimension of array
arr.ndim

1

In [12]:
arr


array([1, 2, 3, 4, 5])

In [ ]:
#return number of elements in each dimension
arr.shape

(5,)

In [15]:
l=[
    [1,2,3],
    [4,5,6]
]
arr2=numpy.array(l)
print(f"{arr2=}")
print(f"{arr2.ndim=}")
print(f"{arr2.shape=}")
print(f"{type(arr2)=}")
print(f'{arr2.dtype=}')



arr2=array([[1, 2, 3],
       [4, 5, 6]])
arr2.ndim=2
arr2.shape=(2, 3)
type(arr2)=<class 'numpy.ndarray'>
arr2.dtype=dtype('int64')


In [26]:
l=[
    [1,2,3],
    [4,5,6]
]
arr2=numpy.array(l,dtype=numpy.float32)
print(f"{arr2=}")
print(f"{arr2.ndim=}")
print(f"{arr2.shape=}")
print(f"{type(arr2)=}")
print(f'{arr2.dtype=}')

arr2=array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)
arr2.ndim=2
arr2.shape=(2, 3)
type(arr2)=<class 'numpy.ndarray'>
arr2.dtype=dtype('float32')


### 3rd Dimension array

##### To find dimension of array

- ND-Array->(n-1)D Array
- N Dimension array has (N-1) Dimensional array ele,emt in 1st dimension<br>
- N Dimensional array has (N-2) Dimensional array element in 2nd dimension<br>

In [32]:
l3=(
    [
        [
        [1,2,3],
        [4,5,6]
        ],   
        [
        [10,20,30],
        [40,50,60]
        ]
        ]   
)
arr3=numpy.array(l3)
print(arr3.shape)
print(arr3)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


### Operations


In [33]:
import numpy as np 

In [42]:
l1=[1,2,3]
l2=[10,20,30]
for ele_1,ele_2 in zip(l1,l2):
    print(ele_1,ele_2)

1 10
2 20
3 30


In [43]:
l1=[1,2,3]
l2=[10,20,30]
result=[]
for ele_1,ele_2 in zip(l1,l2):
    result.append(ele_1+ele_2)
result

[11, 22, 33]

In [40]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

In [41]:
arr1+arr2

array([11, 22, 33, 44])