### Numpy Installation
- !pip install numpy==1.26.4    specific version installation
- !pip install "numpy<=1.26.4"  for conditional installation
- !pip install numpy            install latest version

In [1]:
!pip install numpy

In [2]:
import numpy

In [3]:
list=[1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [4]:
tuple(list)

(1, 2, 3, 4, 5)

### Creating numpy array

In [5]:
arr0=numpy.array(10)
arr0

array(10)

In [6]:
arr0.ndim

0

In [7]:
arr=numpy.array(list)
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
l1=[[[[[[[[[[[[[4,5]]]]]]]]]]]]]
arr1=numpy.array(l1)
arr1.ndim

13

In [10]:
arr1.shape

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2)

In [11]:
# num of dimension of array
arr.ndim

1

In [12]:
arr


array([1, 2, 3, 4, 5])

In [13]:
#return number of elements in each dimension
arr.shape

(5,)

In [14]:
l=[
    [1,2,3],
    [4,5,6]
]
arr2=numpy.array(l)
print(f"{arr2=}")
print(f"{arr2.ndim=}")
print(f"{arr2.shape=}")
print(f"{type(arr2)=}")
print(f'{arr2.dtype=}')



arr2=array([[1, 2, 3],
       [4, 5, 6]])
arr2.ndim=2
arr2.shape=(2, 3)
type(arr2)=<class 'numpy.ndarray'>
arr2.dtype=dtype('int64')


In [15]:
l=[
    [1,2,3],
    [4,5,6]
]
arr2=numpy.array(l,dtype=numpy.float32)
print(f"{arr2=}")
print(f"{arr2.ndim=}")
print(f"{arr2.shape=}")
print(f"{type(arr2)=}")
print(f'{arr2.dtype=}')

arr2=array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)
arr2.ndim=2
arr2.shape=(2, 3)
type(arr2)=<class 'numpy.ndarray'>
arr2.dtype=dtype('float32')


### 3rd Dimension array

##### To find dimension of array

- ND-Array->(n-1)D Array
- N Dimension array has (N-1) Dimensional array ele,emt in 1st dimension<br>
- N Dimensional array has (N-2) Dimensional array element in 2nd dimension<br>

In [16]:
l3=(
    [
        [
        [1,2,3],
        [4,5,6]
        ],   
        [
        [10,20,30],
        [40,50,60]
        ]
        ]   
)
arr3=numpy.array(l3)
print(arr3.shape)
print(arr3)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[10 20 30]
  [40 50 60]]]


### Operations


In [17]:
import numpy as np 

In [18]:
l1=[1,2,3]
l2=[10,20,30]
for ele_1,ele_2 in zip(l1,l2):
    print(ele_1,ele_2)

1 10
2 20
3 30


In [19]:
l1=[1,2,3]
l2=[10,20,30]
result=[]
for ele_1,ele_2 in zip(l1,l2):
    result.append(ele_1+ele_2)
result

[11, 22, 33]

In [20]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])

In [21]:
arr1+arr2

array([11, 22, 33, 44])

In [22]:
np.add(arr1,arr2)

array([11, 22, 33, 44])

In [23]:
np.sum(arr1)

np.int64(10)

In [25]:
arr1*arr2

array([ 10,  40,  90, 160])

In [26]:
np.multiply(arr1,arr2)

array([ 10,  40,  90, 160])

In [27]:
np.dot(arr1,arr2)

np.int64(300)

In [32]:
np.arange(0,12,0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5])

In [34]:
a4=np.arange(0,12,1)   #np.arrange(12)
a4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [35]:
a4.shape

(12,)

In [ ]:
a4.reshape((3,4))  # 3 is row 4 is column it converts 1 dimension array to higher dimension

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
a4.reshape((3,1,4))

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [39]:
arr3.shape

(2, 2, 3)

In [40]:
arr3.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

In [41]:
arr3.reshape(2,3,2,1)

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[10],
         [20]],

        [[30],
         [40]],

        [[50],
         [60]]]])

In [42]:
arr3.flatten()

array([ 1,  2,  3,  4,  5,  6, 10, 20, 30, 40, 50, 60])

In [44]:
arr0=np.array(0.5)
arr1=np.arange(10,16,1)
arr1,arr0

(array([10, 11, 12, 13, 14, 15]), array(0.5))

In [45]:
arr1+arr0

array([10.5, 11.5, 12.5, 13.5, 14.5, 15.5])

In [46]:
arr2=np.array([0.9])
arr2

array([0.9])

In [47]:
arr1+arr2

array([10.9, 11.9, 12.9, 13.9, 14.9, 15.9])

In [48]:
arr3=np.array([1,2])
arr3

array([1, 2])

In [50]:
arr4=np.arange(4).reshape((2,2))
arr4

array([[0, 1],
       [2, 3]])

In [52]:
arr3=np.array([1,2])
arr3

array([1, 2])

In [53]:
arr4+arr3

array([[1, 3],
       [3, 5]])

In [54]:
a5=np.arange(10,101,10)
a5

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [55]:
np.log10(a5)

array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ,
       1.77815125, 1.84509804, 1.90308999, 1.95424251, 2.        ])

In [56]:
np.max(a5)

np.int64(100)

In [ ]:
np.argmax(a5)

np.int64(9)

In [58]:
a6=np.random.randint(10,50,size=(3,3))
a6

array([[27, 41, 33],
       [46, 22, 35],
       [17, 32, 29]], dtype=int32)

In [59]:
a6=np.random.randint(10,50,size=(10,))
a6

array([18, 41, 44, 23, 43, 28, 21, 11, 11, 22], dtype=int32)

In [62]:
np.random.seed(0)
a6=np.random.randint(10,50,size=(3,3))
a6

array([[10, 13, 13],
       [49, 19, 29],
       [31, 46, 33]], dtype=int32)

In [64]:
a6<15

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

In [66]:
a6[a6<15]

array([10, 13, 13], dtype=int32)