## Numpy

In [1]:
import numpy as np


In [3]:
arr_1d=np.array([1,2,3,4])
print("1D Array:",arr_1d)
arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D Array:",arr_2d)

1D Array: [1 2 3 4]
2D Array: [[1 2 3]
 [4 5 6]]


### List vs Numpy Array

In [ ]:
list=[1,2,3,44]
print("Python list multiplication",list*2) #two list within list is created

Python list multiplication [1, 2, 3, 44, 1, 2, 3, 44]


In [5]:
np_array=np.array([1,2,3,4])
print("Multiplication in numpy",np_array*2)

Multiplication in numpy [2 4 6 8]


In [7]:
import time
start=time.time()
py_list=[i*2 for i in range(1000000)]
print("\n List operation time:",time.time()-start)

start=time.time()
np_array=np.arange(100000)*2
print("\n Numpy operation time:", time.time()-start)


 List operation time: 0.22310209274291992

 Numpy operation time: 0.002007007598876953


### Creating array from scratch


In [8]:
zeros=np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
ones=np.ones((4,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
random=np.random.random((2,3))
random

array([[0.46702182, 0.99481839, 0.24378201],
       [0.96741968, 0.91144083, 0.16944027]])

### Vector,Matrix and Tensor

In [17]:
vector=np.array([3,4,5])
print("Vector:\n",vector)

matrix=np.array([[1,2,3],[3,2,5],[5,4,6]])
print("Matrix:\n",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]])
print("Tensor:\n",tensor)

Vector:
 [3 4 5]
Matrix:
 [[1 2 3]
 [3 2 5]
 [5 4 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
